#!/usr/bin/env bash
set -e

echo "deploying latest montagu "

NAME=$(hostname)
MONTAGU_PATH=~/montagu

# We shouldn't need to do this anymore after we've completed this ticket to stop using GitHub auth for vault from servers:
#  https://vimc.myjetbrains.com/youtrack/issue/VIMC-2507
if [ ! -f /vagrant/vault_config ]; then
    echo "Run vault-prepare.sh on host"
    exit 1
fi

. /vagrant/vault_config
export VAULT_ADDR VAULT_AUTH_GITHUB_TOKEN

git -C $MONTAGU_PATH checkout latest
git -C $MONTAGU_PATH submodule update --recursive

(cd $MONTAGU_PATH && sudo -E ./src/deploy.py)

echo "finished deploying latest montagu"