#!/usr/bin/env bash
set -ex

COMPOSE_VERSION=1.22.0

if [ ! -z $DOCKER_LARGE_DISK ]; then
    if [ ! -d $DOCKER_LARGE_DISK ]; then
        echo "Expected a directory at $DOCKER_LARGE_DISK"
        exit 1
    fi

    VAR_LIB_DOCKER="${DOCKER_LARGE_DISK}/docker/var-lib-docker"
    if [ -d $DOCKER_LARGE_DISK/docker/var-lib-docker ]; then
        echo "Docker large disk already configured"
        exit 0
    fi

    if [ -d /var/lib/docker ]; then
        echo "Docker is already configured - can't move it at this point"
        exit 1
    fi

    # The big docker directory is /var/lib/docker - we'll move that
    # out onto the external disk:
    mkdir -p "$VAR_LIB_DOCKER"
    ln -s "$VAR_LIB_DOCKER" /var/lib/docker
fi

if which -a docker > /dev/null; then
    echo "docker is already installed"
else
    echo "installing docker"
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository \
         "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
    sudo apt-get update
    sudo apt-get install -y docker-ce
    for u in "$@"; do
        echo sudo usermod -aG docker "$u"
    done
fi

if which -a docker-compose > /dev/null; then
    echo "docker-compose is already installed"
else
    echo "installing docker-compose"
    sudo curl -L \
         "https://github.com/docker/compose/releases/download/$COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" \
         -o /usr/bin/docker-compose
    sudo chmod +x /usr/bin/docker-compose
fi
