#!/usr/bin/env bash

set -e

apt-get update
apt-get install -y unattended-upgrades curl

cat <<EOF > /etc/apt/apt.conf.d/20auto-upgrades
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
EOF

# In /etc/apt/apt.conf.d/50unattended-upgrades, change two lines from defaults:-
# Uncomment  //Unattended-Upgrade::Remove-Unused-Dependencies "false"   and change value to "true"
# Uncomment  //Unattended-Upgrade::Automatic-Reboot "false"

sed -i 's|//Unattended-Upgrade::Remove-Unused-Dependencies "false"|Unattended-Upgrade::Remove-Unused-Dependencies "true"|' /etc/apt/apt.conf.d/50unattended-upgrades
sed -i 's|//Unattended-Upgrade::Automatic-Reboot "false"|Unattended-Upgrade::Automatic-Reboot "false"|' /etc/apt/apt.conf.d/50unattended-upgrades

# See https://help.ubuntu.com/community/AutomaticSecurityUpdates for documentation:

cat <<EOF > /etc/apt/apt.conf.d/10periodic
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::Verbose 2;
APT::Periodic::RandomSleep 1;
EOF

cat <<EOF > /etc/cron.daily/check_reboot_required
#!/usr/bin/env bash

hostname=\$(uname -n)
if [ \$hostname = "fi--didevimc01" ]; then
  hostname="production"
elif [ \$hostname = "fi--didevimc02" ]; then
  hostname="support"
elif [ \$hostname = "wpia-didess1" ]; then
  hostname="annex"
fi

if [ -f /var/run/reboot-required ]; then
  curl "https://monitor.dide.ic.ac.uk/?machine=\${hostname}.montagu.dide.ic.ac.uk&status=1"
else
  curl "https://monitor.dide.ic.ac.uk/?machine=\${hostname}.montagu.dide.ic.ac.uk&status=0"
fi
EOF

chmod 755 /etc/cron.daily/check_reboot_required
