#!/usr/bin/env bash
set -e

adduser --disabled-password --ingroup montagu

# Warning: these instructions are currently aspirational
sudo -u montagu git clone https://github.com/vimc/montagu-registry \
     ~montagu/registry
sudo -u montagu git clone --recursive https://github.com/vimc/montagu-monitor \
     ~montagu/monitor
sudo -u montagu git clone https://github.com/vimc/montagu-vault \
     ~montagu/vault
