#!/usr/bin/env bash
set -ex

vault_version=0.11.2

if which -a vault > /dev/null; then
    echo "vault is already installed"
else
    echo "installing vault"
    sudo apt-get update
    sudo apt-get install -y unzip
    vault_zip=vault_${vault_version}_linux_amd64.zip
    wget https://releases.hashicorp.com/vault/${vault_version}/$vault_zip
    unzip $vault_zip
    chmod 755 vault
    sudo cp vault /usr/bin/vault
    rm -f $vault_zip vault
fi
