#!/usr/bin/env bash
set -e

export BRANCH=${1:-'latest'}

echo "Building local dev VM with branch: $BRANCH"

HERE=$(dirname $(realpath $0))
MONTAGU_MACHINE_ROOT=$(realpath $HERE/..)
cd $MONTAGU_MACHINE_ROOT

./staging/scripts/deploy-local-vm dev
