#!/usr/bin/env bash
set -e

export BRANCH=${1:-'latest'}

HERE=$(dirname $(realpath $0))
MONTAGU_MACHINE_ROOT=$(realpath $HERE/..)
cd $MONTAGU_MACHINE_ROOT

vagrant destroy dev -f

if [ -f staging/disk/dev.vdi ]; then
  ./staging/scripts/destroy-disk dev
fi

vagrant up dev
