#!/usr/bin/env bash
set -e

# This script runs on the VM itself.

if [ $# -ne 1 ]; then
    echo "Usage: deploy-montagu-branch <ref>"
    exit 1
fi

NAME=$(hostname)
MONTAGU_PATH=~/montagu
REF=$1

echo "deploying montagu '$REF' onto '$NAME'"

# We shouldn't need to do this anymore after we've completed this ticket to stop using GitHub auth for vault from servers:
#  https://vimc.myjetbrains.com/youtrack/issue/VIMC-2507
if [ ! -f /vagrant/vault_config ]; then
    echo "Run restore-prepare.sh on host"
    exit 1
fi

. /vagrant/vault_config
export VAULT_ADDR VAULT_AUTH_GITHUB_TOKEN

git -C $MONTAGU_PATH checkout $REF
git -C $MONTAGU_PATH submodule update --recursive

$MONTAGU_PATH/src/deploy.py

echo "finished deploying montagu $REF"

