#!/usr/bin/env bash
set -e

# This script is designed to run from support  and arranges for
# the vagrant vm to deploy latest
#
# It is called by deploy-latest-to-support which runs on teamcity

HERE=$(dirname $(realpath $0))
MONTAGU_MACHINE_ROOT=$(realpath $HERE/../..)
cd $MONTAGU_MACHINE_ROOT

./staging/scripts/deploy-local-vm latest