#!/usr/bin/env bash
set -e
HERE=$(dirname $(realpath $0))

if [ ! $# -eq 1 ]; then
    echo "Usage: destroy-disk <name>"
    exit 1
fi

VDI_PATH=$HERE/../disk/$1.vdi
if [ ! -f $VDI_PATH ]; then
    echo "Disk not found"
    exit 1
fi

vboxmanage closemedium disk $VDI_PATH --delete
