#!/usr/bin/env bash
set -e

echo "Fetching latest version on Montagu repository into ./montagu"
if [ -d montagu ]; then
    cd montagu && git pull
else
    git clone https://github.com/vimc/montagu.git
    cd montagu
fi

echo "Deploying Montagu"
pip3 install --user -r src/requirements.txt
python3 ./src/deploy.py

