#!/usr/bin/env bash
set -e

# This script runs on the VM itself.  It could be done during
# provisioning, in theory, but this is prone to issues with sudo,
# especially because it seems hard to get the vagrant user to pick up
# the docker group during provisioning.

NAME=$(hostname)
MONTAGU_PATH=~/montagu
VERSION=${1:-latest}

echo "deploying montagu '$VERSION' onto '$NAME'"

# We shouldn't need to do this anymore after we've completed this ticket to stop using GitHub auth for vault from servers:
#  https://vimc.myjetbrains.com/youtrack/issue/VIMC-2507
if [ ! -f /vagrant/vault_config ]; then
    echo "Run vault-prepare.sh on host"
    exit 1
fi

. /vagrant/vault_config
export VAULT_ADDR VAULT_AUTH_GITHUB_TOKEN

git -C $MONTAGU_PATH checkout $VERSION
git -C $MONTAGU_PATH submodule update --recursive

$MONTAGU_PATH/src/deploy.py

echo "finished deploying montagu"
