#!/usr/bin/env bash
set -x
NAME=$(hostname)
MONTAGU_PATH=~/montagu
CONFIG_PATH=/vagrant/config/$NAME

if [ ! -z "$(git -C $MONTAGU_PATH status --short)" ]; then
    echo "Git is not clean - can't continue"
    exit 1
fi

echo "Backing up configuration from $MONTAGU_PATH to $CONFIG_PATH"

mkdir -p $CONFIG_PATH
cp $MONTAGU_PATH/src/montagu-deploy.json $CONFIG_PATH
git -C $MONTAGU_PATH rev-parse HEAD > $CONFIG_PATH/version
